# Generated by VibeNest — plain static HTML site (no build step)
FROM nginx:alpine
COPY . /usr/share/nginx/html
# A repository may have one clearly deployable root document with a descriptive
# filename instead of index.html. Alias only that unambiguous case; never guess
# between multiple pages.
RUN if [ ! -f /usr/share/nginx/html/index.html ]; then \
      set -- /usr/share/nginx/html/*.html; \
      [ "$#" -eq 1 ] && [ -f "$1" ] || { echo "Expected exactly one root HTML entry point"; exit 1; }; \
      cp "$1" /usr/share/nginx/html/index.html; \
    fi
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]